# Generated by Django 5.1.1 on 2024-09-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
    ]
